#!/bin/bash

TMP=Bilder.txt

# for BILD in Pw-*.png 
# do 
#      ZIEL=$(basename "$BILD" ".png")
#     
#     convert "$BILD" "$ZIEL.jpg"
# done

rename s#ü#eu# Pw-*.jpg

for LAND in $(ls -1 Pw-*.jpg | sed 's#Pw-##;s#-0.*##' | sort -u)

do

    ls -1 Pw-${LAND}-0*.jpg \
    | sed 's#^#file "# ; s#$#"#' \
    | tr '"' \' \
    > "$TMP"
    rm ${LAND}.mp4
    ffmpeg -r 5 -f concat -i "$TMP" -vf format=yuv420p ${LAND}.mp4

done
