#!/bin/bash

TMP=Bilder.txt
PREFIX=$1

# for BILD in ${PREFIX}*.png 
# do 
#     ZIEL=$(basename "$BILD" ".png")
#     
#     convert "$BILD" "$ZIEL.jpg"
# done

rename s#ü#eu# ${PREFIX}*.jpg

for LAND in $(ls -1 ${PREFIX}-*.jpg | sed 's#'${PREFIX}'-##; s#-2.*##' | sort -u)

do

    ls -1 ${PREFIX}-${LAND}-*.jpg \
    | sed 's#^#file "# ; s#$#"#' \
    | tr '"' \' \
    > "$TMP"
    rm ${LAND}.mp4
    ffmpeg -r 1 -f concat -i "$TMP" -vf format=yuv420p ${LAND}.mp4

done
